const VALID_TICKERS = new Set<string>();
VALID_TICKERS.add('TSLA')
VALID_TICKERS.add('GOOGL')
VALID_TICKERS.add('SNAP')
VALID_TICKERS.add('AAPL')
VALID_TICKERS.add('SQ')
VALID_TICKERS.add('FB')
VALID_TICKERS.add('AMZN')
VALID_TICKERS.add('NFLX')
VALID_TICKERS.add('AMD')
VALID_TICKERS.add('NVDA')
VALID_TICKERS.add('DOCN')
VALID_TICKERS.add('PYPL')

export default VALID_TICKERS
